const checkKhodham = document.querySelector(".cek");

checkKhodham.addEventListener("click", function () {
  const name = document.getElementById("nameInput").value.trim();
  const resultDiv = document.getElementById("result");

  if (name === "") {
    resultDiv.innerHTML = `<p style ="color : red;">nama tidak boleh kosong!</p>`;
    return;
  }

  const khodamNames = [
    "Biawak Berdiri",
    "Lucifer",
    "Tutup Botol",
    "Monyet sigma",
    "Burung Gerindra",
    "Pohon Beringin Golkar",
    "Banteng PDIP",
    "Ketek Ketulup",
    "Botol Kecap",
    "Raja Bokep",
    "Harimau Sumatra",
    "Tuyul",
    "Kuntilanak daster batik",
    "Gajah Depok",
    "Khodam Kucing Terbang",
    "Sultan Gajah Mini",
    "Tuan Kambing Selam",
    "Mbah Bebek Balap",
    "Jin Burung Gaib",
    "Raja Tikus Bersayap",
    "Khodam Kodok Ganteng",
    "Syeikh Kupu-kupu Baja",
    "Mister Sapi Lincah",
    "Mbah Ayam Ninja",
    "Khodam Singa Berbulu Pink",
    "Tuan Ular Goyang",
    "Dewi Kelelawar Emas",
    "Si Kucing Melata",
    "Mister Jerapah Kerdil",
    "Khodam Zebra Laut",
    "Sultan Kuda Ajaib",
    "Tuan Semut Berkumis",
    "Jin Kura-kura Cepat",
    "Mbah Anjing Bersayap",
    "Khodam Hiu Pelari",
    "Raja Lumba-lumba Terbang",
    "Mister Belalang Hoki",
    "Si Kambing Terbang",
    "Tuan Harimau Mainan",
    "Dewi Gajah Pelangi",
    "Khodam Katak Ninja",
    "Sultan Ayam Berkepala Dua",
    "Mister Ikan Berjalan",
    "Mbah Kelinci Baja",
    "Jin Merpati Misterius",
    "Khodam Sapi Bersirip",
    "Raja Kuda Berkacamata",
    "Mister Beruang Guling",
    "Syeikh Burung Ikan",
    "Khodam Tikus Raksasa",
    "Si Kerbau Lentur",
    "Mbah Naga Kentut",
    "Tuan Kucing Roda Empat",
    "Sultan Cacing Ajaib",
    "Mister Belut Ganteng",
    "Khodam Kuda Laut Kocak",
    "Jin Gajah Miniatur",
    "Raja Bebek Berenang",
    "Mbah Kelelawar Rocker",
    "Khodam Anjing Raksasa",
    "Tuan Kelinci Galaksi",
    "Si Gajah Penari",
    "Mister Naga Berkumis",
    "Dewi Bebek Angkasa",
    "Khodam Lumba-lumba Emas",
    "Raja Kodok Pelari",
    "Jin Semut Baja",
    "Mbah Kambing Anti Gravitasi",
    "Tuan Gajah Berbulu",
    "Sultan Zebra Goyang",
    "Khodam Burung Tidur",
    "Si Sapi Pink",
    "Mbah Ular Gesit",
    "Mister Hiu Hoki",
    "Dewi Ayam Sakti",
    "Raja Tikus Terbang",
    "Tuan Kupu-kupu Baja",
    "Jin Singa Air",
    "Mbah Belalang Emas",
    "Khodam Kucing Air",
    "Si Kuda Baja",
    "Sultan Bebek Emas",
    "Mister Zebra Gaib",
    "Dewi Kura-kura Berkumis",
    "Jin Ikan Pelari",
    "Khodam Ular Naga",
    "Mbah Ayam Penari",
    "Sultan Tikus Raksasa",
    "Raja Burung Baja",
    "Tuan Jerapah Air",
    "Mister Kelinci Lincah",
    "Khodam Semut Kembar",
    "Sultan Singa Gaib",
    "Jin Ayam Berenang",
    "Mbah Gajah Ninja",
    "Tuan Kuda Laut Terbang",
    "Khodam Hiu Emas",
    "Si Sapi Lentur",
    "Mister Harimau Pelangi",
    "Dewi Ular Sakti",
    "Khodam Burung Berkumis",
    "Tuan Kodok Baja",
    "Mbah Kelinci Terbang",
    "Raja Anjing Ninja",
    "Sultan Gajah Berpesta",
    "Jin Kuda Laut Gaib",
    "Khodam Tikus Penari",
    "Mister Belut Lincah",
    "Si Naga Mini",
    "Tuan Merpati Pelangi",
    "Khodam Ikan Terbang",
    "Jembut Naga",
    "Raja Iblis",
    "Macan Ompong",
  ];

  const khodamPresent = Math.random() > 0.5;

  if (khodamPresent) {
    const khodamName =
      khodamNames[Math.floor(Math.random() * khodamNames.length)];
    resultDiv.innerHTML = `<p>${name} memiliki khodam: </p><p style ="color: green; font-weight: bold;">${khodamName} </p>`;
  }
  //   else {
  //     resultDiv.innerHTML = `<p style = "color: red;">Maaf Nama ${name} tidak memiliki khodam. 🙏</p>`;
  //   }
});
